baseURL = 'https://bymarcelolewin.com'
languageCode = 'en-us'
title = 'By Marcelo Lewin'
theme = 'bymarcelolewin'
enableGitInfo = true

[menu]
  [[menu.main]]
    name = "Bio"
    url = "/bio/"
    weight = 10
  [[menu.main]]
    name = "Apps"
    url = "/apps/"
    weight = 20
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 30
  [[menu.main]]
    name = "Contact"
    url = "/bio/"
    weight = 40
  [[menu.main]]
    name = "Discord"
    url = "https://discord.gg/fGegvqH6RD"
    weight = 50

[params]
  author = "Marcelo Lewin"
  description = "I love to build digital products."
  email = "marcelo@redpillbluepillstudios.com"
  linkedin = "https://linkedin.com/in/bymarcelolewin"
  github = "https://github.com/bymarcelolewin"
  npm = "https://www.npmjs.com/~bymarcelolewin"
  youtube = "https://www.youtube.com/@bymarcelolewin"
  twitter = "https://x.com/bymarcelolewin"
  
  # Site versioning
  version = "1.1.2"
  last_updated = "2025-06-24"
